// Scraped from FirstCry - Additional Hindu Names
const scrapedHinduBoyNames = [
    {name:"Aariv",meaning:"King of wisdom, Knowledge, Intelligence",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Aayansh",meaning:"The first Ray of light, Part of parents, Gift of God",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Adhrith",meaning:"Who does not need support but supports everyone",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Advait",meaning:"Unique, Another name for Brahma and Vishnu, Non duality",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Advit",meaning:"Unique, Exclusive",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Akshaj",meaning:"Lord Vishnu, Made from diamond",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Akshat",meaning:"Unwounded, Intact, Lord Shiva, Unscathed",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Amay",meaning:"Lord Ganesh, Free from error, Not cunning",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Anvit",meaning:"Lord Shiva, Reached by the mind, Friend",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Anvith",meaning:"Lord Shiva, Reached by the mind, Companion",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Arhaan",meaning:"Ruler, Tirthankara, Worthy, Emperor",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Arsh",meaning:"Bright, Hero, Truthfulness, Dominion",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Avir",meaning:"Brave, One who fights for peace, Strong",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Avyan",meaning:"Eloquent, One who has no imperfections",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Avyukt",meaning:"Crystal clear, Lord Krishna, Clear mind",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Daivik",meaning:"By the grace of God, Divine, Relating to the gods",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Dakshith",meaning:"Lord Shiva, Derived from Daksh",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Dhanvin",meaning:"Lord Shiva, A name of Lord Rama",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Dhruvit",meaning:"Firm, Constant, Derived from Dhruv (Pole star)",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Divit",meaning:"Immortal, Lord Shiva, Heavenly, Lord Vishnu",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Diyan",meaning:"Bright light, Lamp, Source of Light",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Durja",meaning:"The invincible, One who is invincible",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Eshanth",meaning:"Lord Vishnu, One of the many names of Lord Vishnu",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"E",rashi:"Simha"},
    {name:"Garg",meaning:"Name of a saint, Bull, A sage",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"G",rashi:"Mithun"},
    {name:"Heyansh",meaning:"Part of Lord Krishna",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"H",rashi:"Kark"},
    {name:"Hridhaan",meaning:"Heart, Soul, One who is kind hearted",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"H",rashi:"Kark"},
    {name:"Ivaan",meaning:"Gods gracious gift, The Sun, Ruler",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"I",rashi:"Simha"},
    {name:"Kairav",meaning:"White lotus, Born of water",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Kiyansh",meaning:"Lord Krishna, A modern name variant",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Kriva",meaning:"Lord Krishna, Derived from Lord Krishna",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Kriyansh",meaning:"Lord Krishna, A modern name variant",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Laksh",meaning:"Aim, Target, Goal",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"L",rashi:"Simha"},
    {name:"Manvik",meaning:"One who is conscious, Intelligent, Kind hearted",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Meer",meaning:"Chief, Worthy of admiration",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Nihit",meaning:"God gift, Inherent",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"N",rashi:"Kumbh"},
    {name:"Nirvan",meaning:"Liberation, Salvation, Bliss",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"N",rashi:"Kumbh"},
    {name:"Pranith",meaning:"God like, Derived from praneetham",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"P",rashi:"Kanya"},
    {name:"Reeyansh",meaning:"First Ray of sunlight, Lord Vishnus Ansh",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Ridansh",meaning:"A meaningful part of life",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Ridit",meaning:"World known, One of the Vedas",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rihaan",meaning:"Gods chosen one, Lord Vishnu, Destroyer of enemies",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rishaan",meaning:"Lord Shiva, Good human being",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rishit",meaning:"The best, Learned, One who is the best",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rishiraj",meaning:"King of sage, Ray of light",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Ritvik",meaning:"Priest, Timely, Name of a sage",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rohan",meaning:"Rising, Ascending, Blossoming",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Rudransh",meaning:"Part of Rudra, Name of Lord Shiva",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"R",rashi:"Tula"},
    {name:"Samarth",meaning:"Powerful, Another name for Krishna",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sathvik",meaning:"Calm, Virtuous, another name of Lord Shiva",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Satvik",meaning:"Virtuous, Lord Krishna, Pure, Good",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Satyam",meaning:"Honesty, Truth",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sharvil",meaning:"Lord Krishna, Sacred to Shiva",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shivansh",meaning:"A portion of Lord Shiv",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shlok",meaning:"Hymns of Lord, Verse, Hindu Mantra",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shreyan",meaning:"Good fortune, Lord Vishnu",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shreyansh",meaning:"Fame giver and Lucky, Wealthy",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shrihan",meaning:"Lord Vishnu, Handsome",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shriyan",meaning:"Lord Vishnu, Combination of Shriman and Narayan",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sriansh",meaning:"Born with a part of Lakshmi",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Vedansh",meaning:"Part of Veda",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
    {name:"Viaan",meaning:"Full of life and energy, Alive",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
    {name:"Vivan",meaning:"Lord Krishna, Full of life, Morning rays",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
    {name:"Vishruth",meaning:"Celebrated, Renowned, Famous",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
    {name:"Yaksh",meaning:"Representative of God, Protector of forests",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"Y",rashi:"Makar"},
    {name:"Yuvaan",meaning:"Youthful, Lord Shiva, Young, Healthy",gender:"Boy",religion:"Hindu",origin:"Sanskrit",startingLetter:"Y",rashi:"Makar"},
];

const scrapedHinduGirlNames = [
    {name:"Nitara",meaning:"Deeply rooted, Star",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"N",rashi:"Kumbh"},
    {name:"Shreenika",meaning:"Lotus in the heart of Lord Vishnu, Goddess Lakshmi",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Divisha",meaning:"Goddess Durga, Chief of the Goddess",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Trishika",meaning:"Goddess Lakshmi, Trident",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"T",rashi:"Dhanu"},
    {name:"Kayra",meaning:"Peaceful, Unique, Lady",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Ayra",meaning:"The beginning, The principle, The breathe of life",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Aarvi",meaning:"Peace, One who makes peace",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Srinika",meaning:"Goddess Lakshmi, Lotus in the heart of Lord Vishnu",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Jisha",meaning:"Joyful, Person with highest feelings for living",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"J",rashi:"Tula"},
    {name:"Kashvi",meaning:"Shining, Bright, Glowing, Luminous",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Vedika",meaning:"Full of knowledge, Altar, Consciousness",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
    {name:"Arika",meaning:"Beautiful, Goddess of Wealth and Prosperity",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Saisha",meaning:"With great desire and wish, Truth of life",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Advika",meaning:"World, Earth, Unique",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Amaira",meaning:"The one who will be beautiful forever, Long-lived",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Mayra",meaning:"Beloved, Favorable, Admirable, Marvellous",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Prisha",meaning:"Love, Goddess Laxmi, God's Gift",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"P",rashi:"Kanya"},
    {name:"Aira",meaning:"The beginning, The principle, Breath of life",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Miraya",meaning:"Devotee of Lord Krishna",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Shanaya",meaning:"First Ray of the Sun, Distinguished",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Aashvi",meaning:"Blessed and victorious, Goddess Saraswati",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Anshi",meaning:"God's gift, Part of oneself",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Apeksha",meaning:"Expectation, Hope, Requirement",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Annika",meaning:"Goddess Durga, Grace, Favour",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Ashvika",meaning:"Goddess Santhoshi, Derived from Ashvin",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"A",rashi:"Mesh"},
    {name:"Bhavika",meaning:"Cheerful expression, Well-behaved, Worthy",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Bhuvika",meaning:"Heaven, On earth",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Binita",meaning:"Modest, Humble, Obedient",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Bhavi",meaning:"Future, Emotional, Sentimental",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Bithika",meaning:"Path between trees, Avenue",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Brishti",meaning:"Rain, Shower of blessings",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Chaitra",meaning:"New bright light, First month of Hindu calendar",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"C",rashi:"Mithun"},
    {name:"Chandani",meaning:"Moonlight, A river, Star",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"C",rashi:"Mithun"},
    {name:"Dhwani",meaning:"Sound, Melody, Music",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Drishya",meaning:"Sight, Visible, Worth seeing",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Dishani",meaning:"Goddess of the four directions",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"D",rashi:"Kark"},
    {name:"Krisha",meaning:"Divine, Thin, Goddess name",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Khushi",meaning:"Happiness, Joy, Delight",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Kritika",meaning:"One of the stars, Cluster of stars",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Mishika",meaning:"Gift of God, Love of God",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Manvi",meaning:"Humanly, With humane qualities",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Manya",meaning:"Worthy of honor, Respected",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Meher",meaning:"Grace, Benevolence, Kindness",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"M",rashi:"Simha"},
    {name:"Samaira",meaning:"Enchanting, Guarded by God",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shania",meaning:"Beautiful, On my way",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Saloni",meaning:"Beautiful, Charming, Dark-complexioned",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sania",meaning:"Radiant, Brilliant, Moment in time",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sanjana",meaning:"In harmony, Gentle, Creator",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Pranshi",meaning:"Goddess Lakshmi, Names of the Devi Laxmi",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"P",rashi:"Kanya"},
    {name:"Pavithra",meaning:"Pure, Holy, Virtuous",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"P",rashi:"Kanya"},
    {name:"Payal",meaning:"Anklet, Foot ornament",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"P",rashi:"Kanya"},
    {name:"Sanskriti",meaning:"Culture, Traditional heritage",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sapna",meaning:"Dream, Vision",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sarika",meaning:"Myna bird, Elegant woman",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Seema",meaning:"Boundary, Limit, Face",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shagun",meaning:"Auspicious moment, Omen",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shalini",meaning:"Modest, Shy, Dignified",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shanti",meaning:"Peace, Quiet, Calm",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sharda",meaning:"Goddess of learning, Saraswati",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shivangi",meaning:"Part of Lord Shiva, Auspicious",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shivani",meaning:"Goddess Parvati, Wife of Shiva",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shradha",meaning:"Faith, Trust, Veneration",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shravani",meaning:"Born in Shravan month, Festive",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Srishti",meaning:"Creation, Universe, Nature",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sunita",meaning:"Well-behaved, Mannerly, Polite",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"S",rashi:"Kumbh"},
    {name:"Tanvi",meaning:"Slender, Beautiful, Delicate woman",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"T",rashi:"Dhanu"},
    {name:"Uma",meaning:"Goddess Parvati, Bright, Light",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"U",rashi:"Meen"},
    {name:"Vanya",meaning:"Gracious gift of God, Goddess of forests",gender:"Girl",religion:"Hindu",origin:"Sanskrit",startingLetter:"V",rashi:"Vrishabh"},
];
