// Muslim Names
const muslimNames = [
    // BOY
    { name: "Aariz", meaning: "Respectable man, Intelligent", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Abbas", meaning: "Lion, Stern", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Abdullah", meaning: "Servant of Allah", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Adil", meaning: "Just, Honest, Upright", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Ahmad", meaning: "Praised, One who constantly thanks God", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Ali", meaning: "High, Exalted, Noble", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Aman", meaning: "Peace, Safety", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Anas", meaning: "Friendly, Affectionate", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Arham", meaning: "Most merciful, Most compassionate", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Asad", meaning: "Lion, Lucky, Fortunate", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Ashar", meaning: "Wise, Prudent", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Ayan", meaning: "Gift of God", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Azaan", meaning: "Call to prayer", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Badr", meaning: "Full moon", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bilal", meaning: "Water, Victory", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Danish", meaning: "Wisdom, Learning, Knowledge", gender: "Boy", religion: "Muslim", origin: "Persian", startingLetter: "D", rashi: "Kark" },
    { name: "Ehan", meaning: "Full moon, Expected", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "E", rashi: "Simha" },
    { name: "Fahad", meaning: "Panther, Leopard", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Faisal", meaning: "Decisive, A judge", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Faiz", meaning: "Benefit, Abundance", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Farhan", meaning: "Happy, Delighted", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Fawwaz", meaning: "Successful", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Hamdan", meaning: "One who praises", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Hamza", meaning: "Lion, Strong", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Haris", meaning: "Lion, Guardian, Protector", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Hassan", meaning: "Good, Handsome", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Hussain", meaning: "Good, Handsome, Grandson of Prophet", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Ibrahim", meaning: "Father of nations, Prophet Abraham", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Imran", meaning: "Prosperity, Long-lived", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Irfan", meaning: "Knowledge, Thankfulness", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Ismail", meaning: "God will hear, Prophet Ishmael", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Javed", meaning: "Eternal, Immortal", gender: "Boy", religion: "Muslim", origin: "Persian", startingLetter: "J", rashi: "Tula" },
    { name: "Junaid", meaning: "Warrior, Young fighter", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "J", rashi: "Tula" },
    { name: "Kareem", meaning: "Generous, Noble", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Khalid", meaning: "Eternal, Glorious, Immortal", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Luqman", meaning: "Wise, Intelligent", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "L", rashi: "Simha" },
    { name: "Maaz", meaning: "Refuge, Shelter", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Mahir", meaning: "Skilled, Talented", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Malik", meaning: "King, Master, Ruler", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Minhaj", meaning: "Path, Way, Method", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Mohammed", meaning: "Praised, Praiseworthy", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Moiz", meaning: "One who gives power, Protector", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Mustafa", meaning: "Chosen one, Prophet's name", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Nabeel", meaning: "Noble, Honorable", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nadir", meaning: "Rare, Opposite, Dear", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Noor", meaning: "Light, Divine light", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Omar", meaning: "Long lived, Flourishing", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Qasim", meaning: "Distributor, Divider", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Q", rashi: "Makar" },
    { name: "Rayan", meaning: "Watered, Luxuriant, Gate of Paradise", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Rehan", meaning: "Sweet basil, Fragrant", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Rizwan", meaning: "Pleasure of God, Satisfaction", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Saad", meaning: "Happiness, Luck, Good fortune", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sahil", meaning: "Guide, Shore, Bank of river", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Salman", meaning: "Safe, Peaceful, Protected", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sameer", meaning: "Entertaining companion, Wind", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shahid", meaning: "Witness, One who is present", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shahzeb", meaning: "King's adornment, Suitable for king", gender: "Boy", religion: "Muslim", origin: "Persian", startingLetter: "S", rashi: "Kumbh" },
    { name: "Suhail", meaning: "Gentle, Easy, Star Canopus", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Tariq", meaning: "Morning star, He who knocks", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "T", rashi: "Dhanu" },
    { name: "Umar", meaning: "Life, Long-lived", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "U", rashi: "Meen" },
    { name: "Usman", meaning: "Companion of Prophet, Baby bustard", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "U", rashi: "Meen" },
    { name: "Wahid", meaning: "Unique, Matchless", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "W", rashi: "Kumbh" },
    { name: "Waseem", meaning: "Handsome, Grace", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "W", rashi: "Kumbh" },
    { name: "Yahya", meaning: "God is gracious, Prophet John", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Y", rashi: "Makar" },
    { name: "Yusuf", meaning: "God gives, Prophet Joseph", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Y", rashi: "Makar" },
    { name: "Zaid", meaning: "Growth, Abundance", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
    { name: "Zayn", meaning: "Beauty, Grace, Adornment", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
    { name: "Zubair", meaning: "Strong, Powerful, Brave", gender: "Boy", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
    // GIRL
    { name: "Aabida", meaning: "Worshipper, Devout", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Aafreen", meaning: "Brave, Encouragement", gender: "Girl", religion: "Muslim", origin: "Persian", startingLetter: "A", rashi: "Mesh" },
    { name: "Aayat", meaning: "Verses of holy Quran, Signs", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Afiya", meaning: "Health, Well being", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Aisha", meaning: "Alive, Well-living, Wife of Prophet", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Alina", meaning: "Noble, Soft, Delicate", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Amara", meaning: "Eternal, Graceful beauty", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Amira", meaning: "Princess, Commander", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Anaya", meaning: "Gift of God, Caring", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Arfa", meaning: "High, Exalted, Sublime", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Asma", meaning: "Excellent, Precious, Supreme", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Atiqa", meaning: "Ancient, Noble, Generous", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Azra", meaning: "Virgin, Chaste, unmarried girl", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "A", rashi: "Mesh" },
    { name: "Bushra", meaning: "Good news, Glad tidings", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Dua", meaning: "Prayer, Blessing", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "D", rashi: "Kark" },
    { name: "Elham", meaning: "Inspiration, Intuition", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "E", rashi: "Simha" },
    { name: "Farah", meaning: "Joy, Happiness, Delight", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Fatima", meaning: "Captivating, Daughter of Prophet", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Firdaus", meaning: "Paradise, Heaven", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "F", rashi: "Meen" },
    { name: "Gulnaz", meaning: "Rose, Flower with grace", gender: "Girl", religion: "Muslim", origin: "Persian", startingLetter: "G", rashi: "Mithun" },
    { name: "Hafsa", meaning: "Cub, Young lioness, Wife of Prophet", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Hana", meaning: "Happiness, Bliss", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Hira", meaning: "Diamond", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "H", rashi: "Kark" },
    { name: "Inaya", meaning: "Help, Care, Protection", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Iqra", meaning: "To read, Recite", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "I", rashi: "Simha" },
    { name: "Jasmine", meaning: "A fragrant flower", gender: "Girl", religion: "Muslim", origin: "Persian", startingLetter: "J", rashi: "Tula" },
    { name: "Khadija", meaning: "Early baby, Trustworthy, Wife of Prophet", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kinza", meaning: "Hidden treasure", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Laiba", meaning: "Angel of heaven", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "L", rashi: "Simha" },
    { name: "Laila", meaning: "Night, Dark beauty", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "L", rashi: "Simha" },
    { name: "Maha", meaning: "Large eyes, Moon", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Mahira", meaning: "Skilled, Expert, Talented", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Maira", meaning: "Moon, Admirable", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Maryam", meaning: "Beloved, Pure, Mother of Jesus", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "M", rashi: "Simha" },
    { name: "Nadia", meaning: "Caller, Announcer, Gentle", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Naira", meaning: "Glittering, Shining", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Noor", meaning: "Light, Divine light", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Ramsha", meaning: "Bunch of flowers", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Rida", meaning: "Content, Satisfied", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Ruhi", meaning: "Soul, Spiritual", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "R", rashi: "Tula" },
    { name: "Sana", meaning: "Radiance, Brilliance", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sara", meaning: "Pure, Happy", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sobia", meaning: "Sweet girl, Virtuous", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Tania", meaning: "Fairy queen, Princess", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "T", rashi: "Dhanu" },
    { name: "Tasneem", meaning: "Fountain in paradise", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "T", rashi: "Dhanu" },
    { name: "Uzma", meaning: "Grand, Greatest", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "U", rashi: "Meen" },
    { name: "Wafa", meaning: "Faithfulness, Loyalty", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "W", rashi: "Kumbh" },
    { name: "Yasmin", meaning: "Jasmine flower", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "Y", rashi: "Makar" },
    { name: "Zainab", meaning: "Fragrant flower, Prophet's daughter", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
    { name: "Zara", meaning: "Princess, High status", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
    { name: "Zoya", meaning: "Alive, Loving and caring", gender: "Girl", religion: "Muslim", origin: "Arabic", startingLetter: "Z", rashi: "Meen" },
];
