// Christian Names
const christianNames = [
    // BOY
    { name: "Aaron", meaning: "High mountain, Exalted", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "A", rashi: "Mesh" },
    { name: "Adam", meaning: "Son of the red earth", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "A", rashi: "Mesh" },
    { name: "Adrian", meaning: "From the Adriatic sea region", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "A", rashi: "Mesh" },
    { name: "Alex", meaning: "Defender of the people", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "A", rashi: "Mesh" },
    { name: "Andrew", meaning: "Strong, Manly, Courageous", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "A", rashi: "Mesh" },
    { name: "Anthony", meaning: "Priceless, Praiseworthy", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "A", rashi: "Mesh" },
    { name: "Benjamin", meaning: "Son of the right hand", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bryan", meaning: "Strong, Virtuous, Honorable", gender: "Boy", religion: "Christian", origin: "Celtic", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Caleb", meaning: "Faithful, Wholehearted devotion", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "C", rashi: "Mithun" },
    { name: "Christian", meaning: "Follower of Christ", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "C", rashi: "Mithun" },
    { name: "Christopher", meaning: "Christ-bearer", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "C", rashi: "Mithun" },
    { name: "Daniel", meaning: "God is my judge", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "D", rashi: "Kark" },
    { name: "David", meaning: "Beloved, Darling", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "D", rashi: "Kark" },
    { name: "Dylan", meaning: "Son of the sea", gender: "Boy", religion: "Christian", origin: "Welsh", startingLetter: "D", rashi: "Kark" },
    { name: "Elijah", meaning: "My God is Yahweh", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "E", rashi: "Simha" },
    { name: "Ethan", meaning: "Strong, Firm, Enduring", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "E", rashi: "Simha" },
    { name: "Evan", meaning: "God is gracious", gender: "Boy", religion: "Christian", origin: "Welsh", startingLetter: "E", rashi: "Simha" },
    { name: "Felix", meaning: "Happy, Fortunate", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "F", rashi: "Meen" },
    { name: "Francis", meaning: "Free man, From France", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "F", rashi: "Meen" },
    { name: "Frederick", meaning: "Peaceful ruler", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "F", rashi: "Meen" },
    { name: "Gabriel", meaning: "God is my strength", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "G", rashi: "Mithun" },
    { name: "George", meaning: "Farmer, Earth worker", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "G", rashi: "Mithun" },
    { name: "Gregory", meaning: "Watchful, Alert", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "G", rashi: "Mithun" },
    { name: "Henry", meaning: "Estate ruler", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "H", rashi: "Kark" },
    { name: "Isaac", meaning: "He will laugh, Joy", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "I", rashi: "Simha" },
    { name: "Jacob", meaning: "Supplanter, He who follows", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "James", meaning: "Supplanter", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Jason", meaning: "Healer", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "J", rashi: "Tula" },
    { name: "Jeremy", meaning: "Exalted by the Lord", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Jonathan", meaning: "God has given", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Joseph", meaning: "God will increase", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Joshua", meaning: "God is salvation", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Kevin", meaning: "Handsome, Beautiful birth", gender: "Boy", religion: "Christian", origin: "Irish", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Leo", meaning: "Lion", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "L", rashi: "Simha" },
    { name: "Liam", meaning: "Strong-willed warrior", gender: "Boy", religion: "Christian", origin: "Irish", startingLetter: "L", rashi: "Simha" },
    { name: "Lucas", meaning: "Light, Illumination", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "L", rashi: "Simha" },
    { name: "Luke", meaning: "Light, Bringer of light", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "L", rashi: "Simha" },
    { name: "Mark", meaning: "Of Mars, Warrior", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "M", rashi: "Simha" },
    { name: "Martin", meaning: "Of Mars, Warrior", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "M", rashi: "Simha" },
    { name: "Matthew", meaning: "Gift of God", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "M", rashi: "Simha" },
    { name: "Michael", meaning: "Who is like God", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "M", rashi: "Simha" },
    { name: "Nathan", meaning: "He gave", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nicholas", meaning: "Victory of the people", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "N", rashi: "Kumbh" },
    { name: "Noah", meaning: "Rest, Comfort", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "N", rashi: "Kumbh" },
    { name: "Oliver", meaning: "Olive tree planter, Peace", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Oscar", meaning: "God spear", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Patrick", meaning: "Noble, Patrician", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "P", rashi: "Kanya" },
    { name: "Paul", meaning: "Small, Humble", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "P", rashi: "Kanya" },
    { name: "Peter", meaning: "Rock, Stone", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "P", rashi: "Kanya" },
    { name: "Philip", meaning: "Lover of horses", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "P", rashi: "Kanya" },
    { name: "Richard", meaning: "Powerful ruler, Strong", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "R", rashi: "Tula" },
    { name: "Robert", meaning: "Bright fame", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "R", rashi: "Tula" },
    { name: "Ryan", meaning: "Little king", gender: "Boy", religion: "Christian", origin: "Irish", startingLetter: "R", rashi: "Tula" },
    { name: "Samuel", meaning: "God has heard, Name of God", gender: "Boy", religion: "Christian", origin: "Hebrew", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sebastian", meaning: "Venerable, Revered", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "S", rashi: "Kumbh" },
    { name: "Stephen", meaning: "Crown, Garland", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "S", rashi: "Kumbh" },
    { name: "Thomas", meaning: "Twin", gender: "Boy", religion: "Christian", origin: "Aramaic", startingLetter: "T", rashi: "Dhanu" },
    { name: "Timothy", meaning: "Honoring God", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "T", rashi: "Dhanu" },
    { name: "Victor", meaning: "Conqueror", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vincent", meaning: "Conquering, Prevailing", gender: "Boy", religion: "Christian", origin: "Latin", startingLetter: "V", rashi: "Vrishabh" },
    { name: "William", meaning: "Resolute protector", gender: "Boy", religion: "Christian", origin: "Germanic", startingLetter: "W", rashi: "Kumbh" },
    { name: "Xavier", meaning: "New house, Bright", gender: "Boy", religion: "Christian", origin: "Greek", startingLetter: "X", rashi: "Makar" },
    // GIRL
    { name: "Abigail", meaning: "My father's joy", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "A", rashi: "Mesh" },
    { name: "Alice", meaning: "Noble, Exalted", gender: "Girl", religion: "Christian", origin: "Germanic", startingLetter: "A", rashi: "Mesh" },
    { name: "Amanda", meaning: "Worthy of love", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "A", rashi: "Mesh" },
    { name: "Angela", meaning: "Angel, Messenger of God", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "A", rashi: "Mesh" },
    { name: "Anna", meaning: "Grace, Favor", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "A", rashi: "Mesh" },
    { name: "Bella", meaning: "Beautiful, Devoted to God", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bethany", meaning: "House of figs, From near Jerusalem", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Charlotte", meaning: "Free woman", gender: "Girl", religion: "Christian", origin: "French", startingLetter: "C", rashi: "Mithun" },
    { name: "Chloe", meaning: "Blooming, Fertility", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "C", rashi: "Mithun" },
    { name: "Christina", meaning: "A Christian, Follower of Christ", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "C", rashi: "Mithun" },
    { name: "Diana", meaning: "Divine, Heavenly", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "D", rashi: "Kark" },
    { name: "Dorothy", meaning: "Gift of God", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "D", rashi: "Kark" },
    { name: "Eleanor", meaning: "Bright, Shining one", gender: "Girl", religion: "Christian", origin: "French", startingLetter: "E", rashi: "Simha" },
    { name: "Elizabeth", meaning: "God is my oath, Pledged to God", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "E", rashi: "Simha" },
    { name: "Emily", meaning: "Rival, Industrious, Striving", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "E", rashi: "Simha" },
    { name: "Emma", meaning: "Universal, Whole", gender: "Girl", religion: "Christian", origin: "Germanic", startingLetter: "E", rashi: "Simha" },
    { name: "Eva", meaning: "Life, Living one", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "E", rashi: "Simha" },
    { name: "Faith", meaning: "Trust, Devotion, Belief", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "F", rashi: "Meen" },
    { name: "Florence", meaning: "Flourishing, Prosperous", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "F", rashi: "Meen" },
    { name: "Grace", meaning: "God's grace, Kindness", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "G", rashi: "Mithun" },
    { name: "Hannah", meaning: "Favor, Grace, God has favored me", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "H", rashi: "Kark" },
    { name: "Helen", meaning: "Shining light, Bright one", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "H", rashi: "Kark" },
    { name: "Hope", meaning: "Desire, Expectation", gender: "Girl", religion: "Christian", origin: "English", startingLetter: "H", rashi: "Kark" },
    { name: "Isabella", meaning: "Pledged to God, Consecrated", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "I", rashi: "Simha" },
    { name: "Ivy", meaning: "Faithfulness, Climbing plant", gender: "Girl", religion: "Christian", origin: "English", startingLetter: "I", rashi: "Simha" },
    { name: "Jessica", meaning: "He who sees, Rich", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Joan", meaning: "God is gracious", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Joyce", meaning: "Lord", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "J", rashi: "Tula" },
    { name: "Julia", meaning: "Youthful, Downy", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "J", rashi: "Tula" },
    { name: "Katherine", meaning: "Pure, Clear", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Laura", meaning: "Laurel tree, Symbol of victory", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "L", rashi: "Simha" },
    { name: "Lily", meaning: "Pure, Innocent, Beautiful flower", gender: "Girl", religion: "Christian", origin: "English", startingLetter: "L", rashi: "Simha" },
    { name: "Lucy", meaning: "Light, Illumination", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "L", rashi: "Simha" },
    { name: "Mary", meaning: "Beloved, Bitter, Sea of bitterness", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "M", rashi: "Simha" },
    { name: "Melody", meaning: "Song, Music", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "M", rashi: "Simha" },
    { name: "Michelle", meaning: "Who is like God", gender: "Girl", religion: "Christian", origin: "French", startingLetter: "M", rashi: "Simha" },
    { name: "Naomi", meaning: "Pleasantness, My delight", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "N", rashi: "Kumbh" },
    { name: "Natalie", meaning: "Born on Christmas, Christmas day", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nicole", meaning: "Victory of the people", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "N", rashi: "Kumbh" },
    { name: "Olivia", meaning: "Olive tree, Symbol of peace", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Penelope", meaning: "Weaver, Faithful wife", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "P", rashi: "Kanya" },
    { name: "Rachel", meaning: "Ewe, Innocent", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "R", rashi: "Tula" },
    { name: "Rebecca", meaning: "To tie, To bind, Captivating", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "R", rashi: "Tula" },
    { name: "Ruth", meaning: "Companion, Friend, Vision of beauty", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "R", rashi: "Tula" },
    { name: "Sarah", meaning: "Princess, Lady, Noble woman", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "S", rashi: "Kumbh" },
    { name: "Scarlett", meaning: "Bright red, Scarlet", gender: "Girl", religion: "Christian", origin: "English", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sophia", meaning: "Wisdom", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "S", rashi: "Kumbh" },
    { name: "Susan", meaning: "Lily, Rose", gender: "Girl", religion: "Christian", origin: "Hebrew", startingLetter: "S", rashi: "Kumbh" },
    { name: "Theresa", meaning: "Harvester", gender: "Girl", religion: "Christian", origin: "Greek", startingLetter: "T", rashi: "Dhanu" },
    { name: "Victoria", meaning: "Victory, Conqueror", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vivian", meaning: "Alive, Full of life", gender: "Girl", religion: "Christian", origin: "Latin", startingLetter: "V", rashi: "Vrishabh" },
];

// Sikh Names
const sikhNames = [
    { name: "Amardeep", meaning: "Light of immortality", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Amrit", meaning: "Nectar, Immortal", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Angad", meaning: "A part of God, Beloved", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Arjun", meaning: "Pure, Bright, Pandava warrior", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Baljeet", meaning: "Mighty, Victorious", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Balwinder", meaning: "Strength of the Almighty", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Charanjit", meaning: "One who has won over the Lord", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "C", rashi: "Mithun" },
    { name: "Daljeet", meaning: "Conqueror of forces", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "D", rashi: "Kark" },
    { name: "Fateh", meaning: "Victory", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "F", rashi: "Meen" },
    { name: "Gurkirat", meaning: "One who sings praises of the Guru", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Gurpreet", meaning: "Love of God, Devotee of Guru", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Gursharan", meaning: "Refuge in God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Harjeet", meaning: "God's victory", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Harpreet", meaning: "Lover of God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Harvinder", meaning: "God who is the master of Heaven", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Inder", meaning: "Lord of heaven, Indra", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "I", rashi: "Simha" },
    { name: "Jaskaran", meaning: "Good deeds, Singing praises of God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "J", rashi: "Tula" },
    { name: "Jaspal", meaning: "Protector of fame", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "J", rashi: "Tula" },
    { name: "Jasveer", meaning: "Heroic one", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "J", rashi: "Tula" },
    { name: "Karamjit", meaning: "Victorious by God's grace", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kulwinder", meaning: "The strength of the family", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Lakhveer", meaning: "Brave, Heroic", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "L", rashi: "Simha" },
    { name: "Maninder", meaning: "Lord of the mind", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "M", rashi: "Simha" },
    { name: "Navdeep", meaning: "New light, New lamp", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "N", rashi: "Kumbh" },
    { name: "Navjot", meaning: "New light", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "N", rashi: "Kumbh" },
    { name: "Prabhjot", meaning: "Light of God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "P", rashi: "Kanya" },
    { name: "Ranveer", meaning: "Hero of the battle", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "R", rashi: "Tula" },
    { name: "Satinder", meaning: "Devoted to God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "S", rashi: "Kumbh" },
    { name: "Surjit", meaning: "Immortal, Victorious by God", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "S", rashi: "Kumbh" },
    { name: "Taran", meaning: "Raft, Heaven, Deliverer", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "T", rashi: "Dhanu" },
    { name: "Zorawar", meaning: "Brave, Strong, Forceful", gender: "Boy", religion: "Sikh", origin: "Punjabi", startingLetter: "Z", rashi: "Meen" },
    // Sikh Girl
    { name: "Amandeep", meaning: "Light of peace, Lamp of peace", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Amrit", meaning: "Nectar, Immortal", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Anmolpreet", meaning: "Priceless love of God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "A", rashi: "Mesh" },
    { name: "Bani", meaning: "Words of Guru, Voice", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Divjot", meaning: "Divine light", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "D", rashi: "Kark" },
    { name: "Eknoor", meaning: "One light, God's light", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "E", rashi: "Simha" },
    { name: "Gurleen", meaning: "Absorbed in the Guru", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Gurpreet", meaning: "Love of God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Harleen", meaning: "Engrossed in God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Harsimrat", meaning: "One who remembers God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Japneet", meaning: "One who continuously remembers God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "J", rashi: "Tula" },
    { name: "Jasleen", meaning: "Absorbed in praise of God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "J", rashi: "Tula" },
    { name: "Kawal", meaning: "Lotus flower", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kiranjot", meaning: "Ray of divine light", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Loveleen", meaning: "Absorbed in love", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "L", rashi: "Simha" },
    { name: "Manpreet", meaning: "Heart's love, Love of the mind", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "M", rashi: "Simha" },
    { name: "Mehar", meaning: "Grace, Blessing, Kindness", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "M", rashi: "Simha" },
    { name: "Navneet", meaning: "Ever new, Ever fresh", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "N", rashi: "Kumbh" },
    { name: "Parminder", meaning: "Greatest God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "P", rashi: "Kanya" },
    { name: "Ravneet", meaning: "Like the sun", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "R", rashi: "Tula" },
    { name: "Simran", meaning: "Meditation, Remembrance of God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sukhpreet", meaning: "Love of peace", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "S", rashi: "Kumbh" },
    { name: "Tavleen", meaning: "Captivated by God", gender: "Girl", religion: "Sikh", origin: "Punjabi", startingLetter: "T", rashi: "Dhanu" },
];

// Unisex Names
const unisexNames = [
    { name: "Arya", meaning: "Noble, Great, Truthful", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aadi", meaning: "First, Most important, Beginning", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Angel", meaning: "Messenger of God", gender: "Unisex", religion: "Christian", origin: "Greek", startingLetter: "A", rashi: "Mesh" },
    { name: "Cameron", meaning: "Crooked nose", gender: "Unisex", religion: "Christian", origin: "Scottish", startingLetter: "C", rashi: "Mithun" },
    { name: "Charlie", meaning: "Free man", gender: "Unisex", religion: "Christian", origin: "Germanic", startingLetter: "C", rashi: "Mithun" },
    { name: "Casey", meaning: "Brave in battle, Alert", gender: "Unisex", religion: "Christian", origin: "Irish", startingLetter: "C", rashi: "Mithun" },
    { name: "Eden", meaning: "Delight, Place of pleasure", gender: "Unisex", religion: "Christian", origin: "Hebrew", startingLetter: "E", rashi: "Simha" },
    { name: "Gurbani", meaning: "Words of the Guru", gender: "Unisex", religion: "Sikh", origin: "Punjabi", startingLetter: "G", rashi: "Mithun" },
    { name: "Harpreet", meaning: "Lover of God", gender: "Unisex", religion: "Sikh", origin: "Punjabi", startingLetter: "H", rashi: "Kark" },
    { name: "Jamie", meaning: "Supplanter", gender: "Unisex", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Jordan", meaning: "Flowing down", gender: "Unisex", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Jesse", meaning: "God's gift", gender: "Unisex", religion: "Christian", origin: "Hebrew", startingLetter: "J", rashi: "Tula" },
    { name: "Kiran", meaning: "Ray of light", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kavi", meaning: "Poet, Singer", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Lesley", meaning: "Garden of hollies", gender: "Unisex", religion: "Christian", origin: "Scottish", startingLetter: "L", rashi: "Simha" },
    { name: "Morgan", meaning: "Sea defender", gender: "Unisex", religion: "Christian", origin: "Welsh", startingLetter: "M", rashi: "Simha" },
    { name: "Milan", meaning: "Union, Meeting, Agreement", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Noor", meaning: "Light, Divine light", gender: "Unisex", religion: "Muslim", origin: "Arabic", startingLetter: "N", rashi: "Kumbh" },
    { name: "Navtej", meaning: "New light, New shine", gender: "Unisex", religion: "Sikh", origin: "Punjabi", startingLetter: "N", rashi: "Kumbh" },
    { name: "Phoenix", meaning: "Dark red, Mystic bird", gender: "Unisex", religion: "Christian", origin: "Greek", startingLetter: "P", rashi: "Kanya" },
    { name: "Quinn", meaning: "Descendant of Conn, Sense", gender: "Unisex", religion: "Christian", origin: "Irish", startingLetter: "Q", rashi: "Makar" },
    { name: "Riley", meaning: "Courageous, Valiant", gender: "Unisex", religion: "Christian", origin: "Irish", startingLetter: "R", rashi: "Tula" },
    { name: "Robin", meaning: "Famed, Bright, Shining", gender: "Unisex", religion: "Christian", origin: "Germanic", startingLetter: "R", rashi: "Tula" },
    { name: "Rohan", meaning: "Ascending, Growing", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rowan", meaning: "Little red one, Rowan tree", gender: "Unisex", religion: "Christian", origin: "Irish", startingLetter: "R", rashi: "Tula" },
    { name: "Samar", meaning: "Evening conversation, Reward", gender: "Unisex", religion: "Muslim", origin: "Arabic", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sasha", meaning: "Defender of people", gender: "Unisex", religion: "Christian", origin: "Greek", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shaan", meaning: "Pride, Dignity", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Taylor", meaning: "Tailor, One who makes clothes", gender: "Unisex", religion: "Christian", origin: "English", startingLetter: "T", rashi: "Dhanu" },
    { name: "Veer", meaning: "Brave, Courage", gender: "Unisex", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Zeal", meaning: "Great energy, Enthusiasm", gender: "Unisex", religion: "Christian", origin: "English", startingLetter: "Z", rashi: "Meen" },
];
