// Hindu Boy Names
const hinduBoyNames = [
    { name: "Aarav", meaning: "Peaceful, Sound", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aahan", meaning: "Dawn, First ray of light", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aashish", meaning: "Blessing of God", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Abhay", meaning: "Fearless, Brave", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Abhijit", meaning: "Victorious, Conqueror", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Abhimanyu", meaning: "Proud, Self-respecting, Arjuna's son", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Adarsh", meaning: "Ideal, Principle", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aditya", meaning: "The sun, Son of Aditi", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Advik", meaning: "Unique, Unprecedented", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Agastya", meaning: "Name of a sage, One who humbles the mountain", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Akash", meaning: "Sky, Open space", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Akshay", meaning: "Indestructible, Immortal", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Alok", meaning: "Brightness, Light", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anand", meaning: "Joy, Happiness, Bliss", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anant", meaning: "Infinite, Endless, Lord Vishnu", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anish", meaning: "Lord Vishnu, Good, Supreme", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Ansh", meaning: "Portion, Part of God", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anurag", meaning: "Love, Affection, Devotion", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Arjun", meaning: "White, Clear, The Pandava prince", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Arnav", meaning: "Ocean, Sea, Stream", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aryan", meaning: "Noble, Of the Aryan race", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Atharv", meaning: "Name of the first Veda, Lord Ganesha", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Ayush", meaning: "Long lived", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Bharat", meaning: "India, Fire, Lord Rama's brother", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bhavin", meaning: "Winner, To exist", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bodhi", meaning: "Enlightenment, Awakening", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Chandan", meaning: "Sandalwood, Fragrant", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "C", rashi: "Mithun" },
    { name: "Chirag", meaning: "Lamp, One who enlightens", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "C", rashi: "Mithun" },
    { name: "Darsh", meaning: "Sight, Handsome, Lord Krishna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Deepak", meaning: "Lamp, Light", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Dev", meaning: "God, Divine", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Devansh", meaning: "Part of God", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Dhruv", meaning: "Pole star, Constant, Firm", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Divyansh", meaning: "Part of divinity", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Eshan", meaning: "Lord Shiva, In full control", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "E", rashi: "Simha" },
    { name: "Gagan", meaning: "Sky, Heaven", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Ganesh", meaning: "Lord of people, Remover of obstacles", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Gaurav", meaning: "Honor, Pride, Glory", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Govind", meaning: "Lord Krishna, One who pleases", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Hardik", meaning: "Heartfelt, Sincere", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Harsh", meaning: "Happiness, Joy", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Hemant", meaning: "Winter season, Gold", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Ishaan", meaning: "The sun, Dawn, Lord Shiva", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "I", rashi: "Simha" },
    { name: "Jaidev", meaning: "Victory of God", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Jayant", meaning: "Victorious, God Indra's son", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Jivan", meaning: "Life, Full of life", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Kabir", meaning: "Great, Powerful", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kailash", meaning: "Abode of Shiva, Crystal", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Karan", meaning: "Clever, Ear, Charioteer", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kartik", meaning: "Brave, Son of Lord Shiva", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kiaan", meaning: "Grace of God, Ancient", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Krish", meaning: "Lord Krishna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Krishiv", meaning: "Lord Shiva and Lord Krishna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kunal", meaning: "Lotus, One with beautiful eyes", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Lakshya", meaning: "Target, Aim", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "L", rashi: "Simha" },
    { name: "Lalit", meaning: "Elegant, Beautiful, Playful", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "L", rashi: "Simha" },
    { name: "Mahesh", meaning: "Lord Shiva, Great ruler", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Manav", meaning: "Man, Youth", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Manish", meaning: "God of the mind, Intellect", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Mayank", meaning: "Moon", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Mihir", meaning: "Sun, Solar", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Moksh", meaning: "Salvation, Liberation", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Mohan", meaning: "Attractive, Lord Krishna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Nakul", meaning: "One of the five Pandavas", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Naman", meaning: "Salutation, Bowing", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Neel", meaning: "Blue, Sapphire", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nikhil", meaning: "Complete, Entire", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nirav", meaning: "Quiet, Calm, Peaceful", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Om", meaning: "The sacred syllable of the universe", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Omkar", meaning: "The sound of Om, Lord Shiva", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "O", rashi: "Vrishabh" },
    { name: "Parth", meaning: "Prince, Arjuna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Pavan", meaning: "Wind, Air, Purifier", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Pranav", meaning: "The sacred syllable Om", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Prateek", meaning: "Symbol, Sign", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Rahul", meaning: "Conqueror of all miseries", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rajat", meaning: "Silver-colored, Most precious", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Ravi", meaning: "Sun", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Reyansh", meaning: "First ray of sunlight", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rishabh", meaning: "Superior, Symbol of music", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rohit", meaning: "Red, The sun", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rudra", meaning: "Lord Shiva, The howler", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Samir", meaning: "Early morning fragrance", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sarthak", meaning: "Meaningful, Worthy", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shaurya", meaning: "Bravery, Heroism", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shiv", meaning: "Lord Shiva, Auspicious", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shivam", meaning: "Auspicious, Lord Shiva", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Siddharth", meaning: "One who has attained his goals", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Soham", meaning: "I am He, I am that", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Surya", meaning: "Sun god", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Tarun", meaning: "Young, Tender", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "T", rashi: "Dhanu" },
    { name: "Tejas", meaning: "Sharpness, Brightness", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "T", rashi: "Dhanu" },
    { name: "Ujjwal", meaning: "Bright, Luminous", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "U", rashi: "Meen" },
    { name: "Utsav", meaning: "Festival, Celebration", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "U", rashi: "Meen" },
    { name: "Utkarsh", meaning: "Awakening, High quality", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "U", rashi: "Meen" },
    { name: "Vaibhav", meaning: "Prosperity, Richness", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vedant", meaning: "Hindu philosophy", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vihaan", meaning: "Dawn, Morning", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vikas", meaning: "Progress, Development", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vikram", meaning: "Valour, Bravery", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vishal", meaning: "Huge, Grand, Magnificent", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vivaan", meaning: "Full of life, Lord Krishna", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vivek", meaning: "Wisdom, Knowledge, Discrimination", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Yash", meaning: "Victory, Glory, Fame", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "Y", rashi: "Makar" },
    { name: "Yogesh", meaning: "Lord of yoga, Lord Shiva", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "Y", rashi: "Makar" },
    { name: "Yuvaan", meaning: "Young, Healthy", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "Y", rashi: "Makar" },
    { name: "Zian", meaning: "Self peace", gender: "Boy", religion: "Hindu", origin: "Sanskrit", startingLetter: "Z", rashi: "Meen" },
];

// Hindu Girl Names
const hinduGirlNames = [
    { name: "Aadya", meaning: "First power, Goddess Durga", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aahana", meaning: "Inner light, Born during the day", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aaradhya", meaning: "Worshipped, Blessing of Lord Ganesh", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aarohi", meaning: "A music tune, Rising", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aditi", meaning: "Free, Boundless, Goddess of earth", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Ahana", meaning: "Inner light, Dawn", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Alina", meaning: "Beautiful, Noble", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Amaya", meaning: "Night rain, End", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Amisha", meaning: "Pure, Without deceit", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Amrita", meaning: "Immortal, Divine nectar", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Ananya", meaning: "Matchless, Unique", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anika", meaning: "Grace, Goddess Durga, Stone", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Anvi", meaning: "Goddess of the forest, Kind", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Aparna", meaning: "Goddess Parvati, Without leaves", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Avni", meaning: "Earth, The world", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "A", rashi: "Mesh" },
    { name: "Bhavna", meaning: "Feelings, Imagination", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Bhavya", meaning: "Grand, Splendid, Virtuous", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "B", rashi: "Vrishabh" },
    { name: "Chandni", meaning: "Moonlight, Moonbeam", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "C", rashi: "Mithun" },
    { name: "Chahat", meaning: "Love, Wish, Desire", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "C", rashi: "Mithun" },
    { name: "Charvi", meaning: "Beautiful girl", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "C", rashi: "Mithun" },
    { name: "Diya", meaning: "Lamp, Light, Dazzling", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Divya", meaning: "Divine, Brilliant", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Drisha", meaning: "Mountain lord", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "D", rashi: "Kark" },
    { name: "Esha", meaning: "Desire, Purity", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "E", rashi: "Simha" },
    { name: "Gauri", meaning: "Goddess Parvati, Fair complexion", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Gayatri", meaning: "A sacred mantra, Goddess of wisdom", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "G", rashi: "Mithun" },
    { name: "Hansika", meaning: "Swan, Beautiful", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Harshita", meaning: "Full of joy, Happy", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Hima", meaning: "Snow, Ice", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "H", rashi: "Kark" },
    { name: "Isha", meaning: "Goddess Durga, One who protects", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "I", rashi: "Simha" },
    { name: "Ishita", meaning: "One who desires to lead, Mastery", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "I", rashi: "Simha" },
    { name: "Jhanvi", meaning: "River Ganga", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Jiya", meaning: "Sweetheart, Life", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Jyoti", meaning: "Light, Flame", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "J", rashi: "Tula" },
    { name: "Kavya", meaning: "Poetry in motion", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Kiara", meaning: "Bright, Clear, Famous", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Komal", meaning: "Soft, Gentle, Beautiful", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "K", rashi: "Vrishchik" },
    { name: "Lakshmi", meaning: "Goddess of wealth and prosperity", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "L", rashi: "Simha" },
    { name: "Lavanya", meaning: "Grace, Beauty, Loveliness", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "L", rashi: "Simha" },
    { name: "Leela", meaning: "Divine play, Amorous play", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "L", rashi: "Simha" },
    { name: "Madhuri", meaning: "Sweet, Pleasing, Sweetness", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Mahi", meaning: "Earth, River", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Meera", meaning: "Devotee of Lord Krishna", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Mishti", meaning: "Sweet", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Myra", meaning: "Beloved, Aristocratic Lady", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "M", rashi: "Simha" },
    { name: "Nandini", meaning: "A holy cow, Delightful, Goddess Parvati", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Navya", meaning: "Worth Praising, Young", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nisha", meaning: "Night", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Nyra", meaning: "Rose, Beauty of Goddess Saraswati", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "N", rashi: "Kumbh" },
    { name: "Pari", meaning: "Beauty, Fairy, Angel", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Pihu", meaning: "Sweet Sound, A small bird", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Prachi", meaning: "East, Morning, Dawn", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Priya", meaning: "Beloved, Dear one", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Priyanka", meaning: "Lovable, Beloved", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "P", rashi: "Kanya" },
    { name: "Radhika", meaning: "Goddess Radha, Prosperous", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Rashmi", meaning: "Ray of light, Sunbeam", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Reva", meaning: "Star, River Narmada", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Ridhi", meaning: "Fortune, Prosperity", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Riya", meaning: "Singer, Graceful", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "R", rashi: "Tula" },
    { name: "Saanvi", meaning: "Goddess Lakshmi, One to be followed", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sakshi", meaning: "Witness, Eyes", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sanvi", meaning: "Knowledge, Goddess Lakshmi", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sanya", meaning: "Born on Saturday, Radiant", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Saraswati", meaning: "Goddess of knowledge and arts", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shreya", meaning: "Auspicious, Good fortune", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Shruti", meaning: "Musical notes, The Vedas", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Siya", meaning: "Goddess Sita", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Sneha", meaning: "Love, Affection", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Swara", meaning: "Voice, Musical notes", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "S", rashi: "Kumbh" },
    { name: "Tara", meaning: "Star, Goddess Tara", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "T", rashi: "Dhanu" },
    { name: "Trisha", meaning: "Noble, Aristocratic", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "T", rashi: "Dhanu" },
    { name: "Urvi", meaning: "Earth, Vast like the earth", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "U", rashi: "Meen" },
    { name: "Vamika", meaning: "Goddess Durga", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vanshika", meaning: "Flute, Belonging to dynasty", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Varsha", meaning: "Rain, Year", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Veda", meaning: "Sacred knowledge, Wisdom", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Vidya", meaning: "Knowledge, Wisdom", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "V", rashi: "Vrishabh" },
    { name: "Yashvi", meaning: "Famous, Glorious", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "Y", rashi: "Makar" },
    { name: "Zara", meaning: "Princess, Flower in bloom", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "Z", rashi: "Meen" },
    { name: "Ziva", meaning: "Brilliance, Light of God", gender: "Girl", religion: "Hindu", origin: "Sanskrit", startingLetter: "Z", rashi: "Meen" },
];
