// Scraped from FirstCry - Additional Muslim Names
const scrapedMuslimNames = [
    {name:"Shayan",meaning:"Intelligent, Courteous, Worthy",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Mihran",meaning:"Name of a companion of the prophet, A rain of kindness",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Suhaan",meaning:"Very good, Pleasant, Beautiful",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Keyan",meaning:"Crown, King, Royal",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Kiyan",meaning:"Kings, Royal",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"K",rashi:"Vrishchik"},
    {name:"Adyan",meaning:"Name of a prophet, Religious, Pious",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Nahiyan",meaning:"Stopper, Who discourages from doing wrong",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"N",rashi:"Kumbh"},
    {name:"Aidan",meaning:"Help, Intelligent, Helper, Fire, Fiery",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Ashaz",meaning:"One in a million, Name of a companion of the Prophet",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Raahil",meaning:"One who shows the way, Traveler, Path guider",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"R",rashi:"Tula"},
    {name:"Aaban",meaning:"More clear, 8th Persian month, Name of the Angel",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Zayan",meaning:"Bright, Graceful, Beautiful",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"Z",rashi:"Meen"},
    {name:"Armaan",meaning:"Longing, Hope, Desire",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Ahsan",meaning:"Better, Superior, Best of all",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Farid",meaning:"Unique, Precious, One of a kind, Unmatched",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"F",rashi:"Meen"},
    {name:"Fazal",meaning:"Grace, Excellent, Best, Generosity",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"F",rashi:"Meen"},
    {name:"Fauzan",meaning:"Success, Victorious, Salvation",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"F",rashi:"Meen"},
    {name:"Faizan",meaning:"Grace, Favor, Beneficence, Great distribution",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"F",rashi:"Meen"},
    {name:"Ehsan",meaning:"Kindness, Perfection, Excellence, Favor",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"E",rashi:"Simha"},
    {name:"Edrees",meaning:"A prophet's name, To learn, Teacher",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"E",rashi:"Simha"},
    {name:"Taher",meaning:"Pure, Chaste, Clean, Modest, Holy",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"T",rashi:"Dhanu"},
    {name:"Hamzah",meaning:"Lion, Name of the prophet's uncle, Strong and steadfast",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"H",rashi:"Kark"},
    {name:"Safwan",meaning:"Rocks, One who is like a rock, smooth and pure",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Shazil",meaning:"A noble person",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Ayaz",meaning:"Cool breeze, Night breeze",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Bassam",meaning:"Smiling, One who smiles a lot",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Basit",meaning:"One who spreads or grants abundantly",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Bashir",meaning:"Bringer of good news, Herald, Messenger",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"B",rashi:"Vrishabh"},
    {name:"Barakat",meaning:"Blessings, Prospers, Good luck",gender:"Boy",religion:"Muslim",origin:"Arabic",startingLetter:"B",rashi:"Vrishabh"},
    // Girl
    {name:"Aiza",meaning:"Noble, Respected, Having high place in the society",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Aliza",meaning:"Joy, Joyous, Joyful, Blissful",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Suhana",meaning:"Beautiful and pleasant",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Sehrish",meaning:"Sunrise, Enchanting and fascinating personality",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Rayna",meaning:"Beautiful princess, Night, Pure, Clean, Queen",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"R",rashi:"Tula"},
    {name:"Aizah",meaning:"Replacement, Noble",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Manha",meaning:"Gift of Allah, A direction, a path of life",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Eira",meaning:"Snow, The beginning, The breath of life",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"E",rashi:"Simha"},
    {name:"Shiza",meaning:"A gift, A present",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Aaliya",meaning:"Excellent, Highest social standing, Tall, Towering",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Zaina",meaning:"Beauty, Friend, Beloved, Beautiful, Adornment",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"Z",rashi:"Meen"},
    {name:"Amara",meaning:"Immortal one, Unfading flower, Eternal",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Maham",meaning:"Full Moon, Moon light",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Mehreen",meaning:"Loving nature, A bright and beautiful female",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Mavisha",meaning:"Blessing of life, Blessing of God",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Aatika",meaning:"Flower, Good smell",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Mariya",meaning:"Beloved, Beautiful, Purity, Holy",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Jannat",meaning:"Heaven, Paradise",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"J",rashi:"Tula"},
    {name:"Rumaisa",meaning:"Bunch of flowers, Wind that scatters dust",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"R",rashi:"Tula"},
    {name:"Hoorain",meaning:"Beautiful eyes, Beautiful friend of paradise",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"H",rashi:"Kark"},
    {name:"Haya",meaning:"Modesty, Shyness, Bashfulness, Humility",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"H",rashi:"Kark"},
    {name:"Ayesha",meaning:"Prosperous, Living, Favorite wife of Prophet Mohammed",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Madiha",meaning:"Praiseworthy, Commendable",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Atifa",meaning:"Affectionate, Compassionate, Sympathetic",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Anum",meaning:"Blessing of God, Fragrance, God's Gift",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Adira",meaning:"Strong, Noble, Majestic, Powerful",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Aaliyah",meaning:"Exalted, Noble, Highest social standing",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Afsa",meaning:"Prophet Mohammed's wife, Pretty",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Sehar",meaning:"Dawn, Early morning, Beautiful",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
    {name:"Alveera",meaning:"Speaker of truth, Originality and perseverance",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Minha",meaning:"Gift, A blessing from the Almighty",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"M",rashi:"Simha"},
    {name:"Amayra",meaning:"Princess, Beautiful forever",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Amyra",meaning:"Leader, Princess, Royal lady",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"A",rashi:"Mesh"},
    {name:"Samaira",meaning:"Enchanting, Protected by God",gender:"Girl",religion:"Muslim",origin:"Arabic",startingLetter:"S",rashi:"Kumbh"},
];
